#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


PCRE_VERSION='8.34'
NGINX_VERSION='1.4.4'

PCRE_NAME="pcre-${PCRE_VERSION}"
NGINX_NAME="nginx-${NGINX_VERSION}"

PCRE_URL="ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/${PCRE_NAME}.tar.gz"
NGINX_URL="http://nginx.org/download/${NGINX_NAME}.tar.gz"

BUILD_DIR=${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}/build
PCRE_BUILD_DIR=${BUILD_DIR}/${PCRE_NAME}
NGINX_BUILD_DIR=${BUILD_DIR}/${NGINX_NAME}


INSTALL_DIR=${OPENSHIFT_DATA_DIR}
TEMPLATES_DIR=${OPENSHIFT_REPO_DIR}/.openshift/templates


function build_nginx()
{
	mkdir -p ${PCRE_BUILD_DIR}
	mkdir -p ${NGINX_BUILD_DIR}

	echo "Downloading $PCRE_NAME and $NGINX_NAME sources..."
	echo "----------------------------------------------------------------------------------"
	cd ${BUILD_DIR}
	wget ${PCRE_URL} >/dev/null 2>&1
	wget ${NGINX_URL} >/dev/null 2>&1

	echo "Decompressing tar.gz files..."
	echo "----------------------------------------------------------------------------------"
	tar xf ${PCRE_NAME}.tar.gz
	tar xf ${NGINX_NAME}.tar.gz

    echo "Running configure script..."
    echo "----------------------------------------------------------------------------------"
	cd ${NGINX_NAME}
	./configure --prefix=${INSTALL_DIR}/nginx --with-pcre=${PCRE_BUILD_DIR} --with-http_ssl_module >/dev/null 2>&1
	make >/dev/null 2>&1
	make install >/dev/null 2>&1
	make clean >/dev/null 2>&1

	mkdir -p ${INSTALL_DIR}/nginx/run

	cd ${OPENSHIFT_HOMEDIR}
	rm -rf ${BUILD_DIR}
}


function check_and_install_nginx()
{
	if [[ ! -e ${INSTALL_DIR}/nginx/sbin/nginx ]]
    then
		build_nginx
    else
        echo "Nginx is already installed. Not continuing with build..."
	fi
}


check_and_install_nginx
