#!/bin/bash
# The logic to stop your application should be put in this script.
kill `ps -ef | grep hellotornado | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
INSTALL_DIR=${OPENSHIFT_HOMEDIR}/app-root/runtime

echo "Stopping nginx."
kill -QUIT `cat ${INSTALL_DIR}/nginx/run/nginx.pid`
exit 0
